const text = (field_name) => Object.freeze({ field_name, type: 1, ui_type: "Text" });
const date = (field_name) => Object.freeze({ field_name, type: 5, ui_type: "DateTime", property: { date_formatter: "yyyy/MM/dd HH:mm" } });
const currency = (field_name) => Object.freeze({ field_name, type: 2, ui_type: "Currency", property: { currency_code: "VND", formatter: "0" } });
const url = (field_name) => Object.freeze({ field_name, type: 15, ui_type: "Url" });

export const LARK_SCHEMAS = Object.freeze({
  orders: Object.freeze([
    text("ID định danh (TTS)"),
    text("Mã đơn hàng"),
    text("Mã vận đơn"),
    date("Ngày tạo đơn"),
    date("Thời gian thanh toán"),
    text("Trạng thái"),
    currency("Tổng tiền"),
    currency("Tổng tiền tạm tính"),
    currency("Giảm giá sàn"),
    currency("Giảm giá người bán"),
    currency("Tổng giá gốc sản phẩm"),
    currency("Phí vận chuyển"),
    text("Lý do huỷ"),
    currency("Thuế"),
    currency("Thuế sản phẩm"),
    text("Tên shop"),
    currency("Phí xử lý"),
    text("Nơi xử lý đơn"),
    date("Thời hạn tự huỷ đơn"),
    text("Người khởi tạo huỷ"),
    text("ID gói hàng"),
    date("Thời gian huỷ"),
    date("Thời hạn giao hàng"),
    date("Thời gian giao hàng"),
    text("Nền tảng thương mại"),
    text("Đơn vị VC"),
    date("RTS time"),
    url("Video đóng hàng"),
    text("Nhân viên đóng hàng"),
  ]),
  orderItems: Object.freeze([
    text("ID định danh (TTS)"),
    text("Mã đơn hàng"),
    text("Mã Item"),
    text("Mã vận đơn"),
    date("Ngày tạo đơn"),
    text("Mã SKU"),
    text("Mã sản phẩm"),
    text("Tên sản phẩm"),
    text("Là quà tặng?"),
    text("Trạng thái"),
    text("Tên shop"),
    currency("Giá bán lẻ của quà tặng"),
    currency("Giảm giá sàn"),
    currency("Giảm giá người bán"),
    currency("Giá gốc"),
    currency("Giá bán sản phẩm"),
    currency("Giá vốn"),
  ]),
  finance: Object.freeze([
    text("ID định danh (TTS)"),
    date("Ngày tạo đơn"),
    date("Ngày quyết toán"),
    text("Mã statemen"),
    text("Mã đơn hàng"),
    text("Mã giao dịch"),
    text("Mã điều chỉnh"),
    text("Loại giao dịch"),
    text("ID Shop"),
    text("Tên Shop"),
    currency("Doanh thu (Gross)"),
    currency("Thực thu (Net)"),
    currency("Tổng phí & thuế"),
    currency("Số tiền điều chỉnh"),
    currency("Phí ship người bán"),
    currency("Khách hàng thanh toán"),
    currency("Hoàn tiền cho khách"),
    currency("Phí CFV (Sàn)"),
    currency("Hoàn phí CFV (Sàn)"),
    currency("Giảm giá sàn"),
    currency("Hoàn giảm giá sàn"),
    currency("Phí giao hàng bán lẻ"),
    currency("Thanh toán phí giao hàng bán lẻ"),
    currency("Hoàn phí giao hàng bán lẻ"),
    currency("Thuế bán hàng"),
    currency("Thanh toán thuế bán hàng"),
    currency("Hoàn thuế bán hàng"),
    currency("Phí CFV (Người bán)"),
    currency("Hoàn phí CFV (Người bán)"),
    currency("Tổng tiền tạm tính trước giảm giá"),
    currency("Hoàn tiền trước giảm giá"),
    currency("Giảm giá người bán"),
    currency("Hoàn giảm giá người bán"),
    currency("Hoa hồng Affiliate Ads"),
    currency("Hoa hồng Affiliate"),
    currency("Hoa hồng Affiliate (trước PIT)"),
    currency("Hoa hồng đối tác Affiliate"),
    currency("Phí Live Specials"),
    currency("Phí nền tảng (Platform Commission)"),
    currency("Phí đặt trước (Pre-order)"),
    currency("Phí giao dịch (Transaction Fee)"),
    currency("Phí cơ sở hạ tầng (Infrastructure Fee)"),
    currency("Phí Voucher Xtra"),
    currency("Phí Piship"),
    currency("Thuế thu nhập cá nhân (PIT)"),
    currency("Thuế VAT"),
    currency("Phí vận chuyển thực tế"),
    currency("Giảm giá phí vận chuyển"),
    currency("Giảm phí vận chuyển từ nền tảng"),
  ]),
  unsettledTransactions: Object.freeze([
    text("ID định danh (TTS)"),
    date("Ngày tạo đơn"),
    text("Mã đơn hàng"),
    text("Mã giao dịch"),
    text("Mã điều chỉnh"),
    text("Loại giao dịch"),
    text("ID Shop"),
    text("Tên Shop"),
    text("Trạng thái"),
    text("Lý do chưa quyết toán"),
    text("Dự kiến quyết toán"),
    currency("Doanh thu (Gross)"),
    currency("Thực thu (Net)"),
    currency("Tổng phí & thuế"),
    currency("Số tiền điều chỉnh"),
    currency("Phí ship người bán"),
    currency("Tổng tiền tạm tính trước giảm giá"),
    currency("Hoàn tiền trước giảm giá"),
    currency("Giảm giá người bán"),
    currency("Hoàn giảm giá người bán"),
    currency("Hoa hồng Affiliate Ads"),
    currency("Hoa hồng Affiliate"),
    currency("Hoa hồng Affiliate (trước PIT)"),
    currency("Hoa hồng đối tác Affiliate"),
    currency("Phí Live Specials"),
    currency("Phí nền tảng (Platform Commission)"),
    currency("Phí đặt trước (Pre-order)"),
    currency("Phí giao dịch (Transaction Fee)"),
    currency("Phí cơ sở hạ tầng (Infrastructure Fee)"),
    currency("Phí Voucher Xtra"),
    currency("Phí Piship"),
    currency("Thuế thu nhập cá nhân (PIT)"),
    currency("Thuế VAT"),
    currency("Phí vận chuyển thực tế"),
    currency("Giảm giá phí vận chuyển"),
    currency("Giảm phí vận chuyển từ nền tảng"),
    currency("Phí vận chuyển khách trả"),
    currency("Phí dịch vụ COD"),
    currency("Hoàn phí dịch vụ COD"),
  ]),
  returnOrders: Object.freeze([
    text("ID định danh (TTS)"),
    text("Mã đơn hàng"),
    text("Mã trả hàng"),
    text("Mã trả hàng gộp"),
    date("Ngày tạo"),
    text("Phương thức bàn giao"),
    text("Trả hàng gộp"),
    text("Phương thức trả hàng"),
    text("ID đơn vị vận chuyển"),
    text("Tên đơn vị vận chuyển"),
    text("Lý do trả hàng"),
    text("Trạng thái trả hàng"),
    text("Sản phẩm trả hàng"),
    text("Mã vận đơn trả hàng"),
    url("Video trả hàng"),
    text("Loại trả hàng"),
    text("Vai trò"),
    text("Loại vận chuyển"),
    date("Thời gian cập nhật"),
    text("ID Shop"),
    text("Tên Shop"),
    currency("Phí ship được refund"),
    currency("Subtotal refund"),
    currency("Thuế được refund"),
    currency("Tổng refund"),
    currency("Giảm giá nền tảng (sản phẩm)"),
    currency("Giảm giá người bán (sản phẩm)"),
    currency("Giảm giá vận chuyển nền tảng"),
    currency("Giảm giá vận chuyển người bán"),
    currency("Phí trả hàng do người mua trả"),
    currency("Phí trả hàng nền tảng trả"),
    currency("Phí trả hàng người bán trả"),
  ]),
  skus: Object.freeze([
    text("id_sku"),
    text("seller_sku"),
    text("sku_name"),
    text("product_id"),
    text("product_name"),
  ]),
});

const NORMALIZED_TYPE_BY_LARK_TYPE = Object.freeze({ 1: "text", 2: "number", 3: "text", 5: "datetime", 15: "url" });
export const LARK_FIELD_TYPES = Object.freeze(Object.fromEntries(
  Object.values(LARK_SCHEMAS).flat().map((field) => [field.field_name, NORMALIZED_TYPE_BY_LARK_TYPE[field.type] ?? "auto"]),
));

export function buildTestTableDefinitions() {
  const definitions = [];
  for (let month = 1; month <= 12; month += 1) {
    definitions.push({ type: "orders", month, name: `Tiktok Orders K (T${month})`, fields: LARK_SCHEMAS.orders });
    definitions.push({ type: "orderItems", month, name: `Tiktok Order Items K (T${month})`, fields: LARK_SCHEMAS.orderItems });
    definitions.push({ type: "finance", month, name: `Finance Cty Hân Korea (T${month})`, fields: LARK_SCHEMAS.finance });
  }
  definitions.push({ type: "returnOrders", month: null, name: "Return Orders Shop K", fields: LARK_SCHEMAS.returnOrders });
  definitions.push({ type: "skus", month: null, name: "SKUS Tiktok", fields: LARK_SCHEMAS.skus });
  definitions.push({
    type: "unsettledTransactions",
    month: null,
    name: "Unsettled Transactions Cty Hân Korea",
    fields: LARK_SCHEMAS.unsettledTransactions,
  });
  return definitions;
}
